[package]
name = "sunder"
version = "0.0.1"
edition = "2024"
description = "Hopefully a good disassembler one day"
authors = ["Stipulations"]

license = "MIT"

[dependencies]
goblin = "0.10.3"
gpui = "0.2.2"
gpui-component = "0.4.1"
iced-x86 = "1.21.0"
